[jobs.private-doc]
command = ["cargo", "doc", "--no-deps", "--document-private-items"]
need_stdout = true
watch = ["src"]

[jobs.private-doc-open]
command = ["cargo", "doc", "--no-deps", "--document-private-items", "--open"]
need_stdout = true
watch = ["src"]

[jobs.llvm-cov]
command = ["cargo", "llvm-cov"]
need_stdout = true
watch = ["src"]

[jobs.llvm-cov-open]
command = ["cargo", "llvm-cov", "--open"]
need_stdout = true
watch = ["src"]

[jobs.mutants]
command = ["sh", "-c", "cargo mutants -v 2>&1 | cat"]
need_stdout = true
watch = ["src"]

[keybindings]
d = "job:private-doc"
shift-d = "job:private-doc-open"
v = "job:llvm-cov"
shift-v = "job:llvm-cov-open"
m = "job:mutants"
